BlogWebsite/BlogWebsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    path('blog/', include("blog.urls")),
 

   
]

BlogWebsite/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('',views.home, name='home_view'),
    path('add_post/',views.add_post,name='add_post_view'),
    path('all_post/',views.view_post,name='all_post_view'),
    path('detail/<post_id>/',views.detail_posts,name="detail_post_view"),
    path('update/<post_id>/',views.update_post,name='update_post_view'),
    path('delet/<post_id>/', views.delet_post,name='delet_post_view'),
    path('search_result/', views.search_feature, name='search_result_view')
]

BlogWebsite/main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path('', views.home_view, name="home_view"),

]

BlogWebsite/blog/models.py
from django.db import models

# Create your models here.


class Post(models.Model):
    category_choices = (('programing language','programing language'),('DataBase','DataBase'),('artificial intelligence','artificial intelligence'),('internet of things','internet of things'))

    title = models.CharField(max_length=2048)
    content = models.TextField()
    category = models.CharField(max_length=256 , choices=category_choices)
    publish_date =models.DateTimeField()

BlogWebsite/blog/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse
from .models import Post
from django.http import Http404


# Create your views here.


def home(request:HttpRequest):
    
    return render(request,'blog/home.html')


def add_post(request:HttpRequest):
    if request.method == 'POST':
        new_post = Post(title=request.POST['title'], content=request.POST['content'], category=request.POST['category'], publish_date=request.POST['publish_date'])
        new_post.save()

        return redirect("blog:all_post_view")

    return render(request,'blog/add_post.html' , {"Post" : Post.category_choices})


def view_post(request:HttpRequest):
    posts = Post.objects.all().order_by('title')

    return render(request,'blog/all_post.html', context={'posts':posts} )


def detail_posts(request:HttpRequest, post_id):
    try:
        posts = Post.objects.get(id=post_id)
        return render (request,'blog/detail_posts.html', {'posts':posts})
    except Post.DoesNotExist:
       raise Http404("Given post not found....")



    
        
    
        


def update_post(request:HttpRequest, post_id):
    posts = Post.objects.get(id=post_id)

    if request == 'POST':
        Post.title = request.POST['title']
        Post.content = request.POST['content']
        Post.category = request.POST['category']
        Post.publish_date = request.POST['publish_date']
        posts.save()

        return redirect('blog:detail_post_view', post_id=posts.id)
    

    return render(request,'blog/ubdate_posts.html',{'posts':posts})




def delet_post(request:HttpRequest, post_id):
    posts = Post.objects.get(id=post_id)
    posts.delete()

    return redirect('blog:all_post_view')




def search_feature(request):
    
    if request.method== 'POST':
        search_query = request.POST['search_query']
        posts = Post.objects.filter(title__contains=search_query)
        return render(request, 'blog/all_post.html', {'query':search_query, 'posts':posts})

def category(request,post_choices):
    if request.method=='POSt':
        pass



    

BlogWebsite/main/views.py
from django.shortcuts import render , redirect
from django.http import HttpRequest , HttpResponse
from blog.models import Blog

# Create your views here.

def home_view(request : HttpRequest):


    return render(request, "main/index.html")



def Search_view(request:HttpRequest):
    blog=Blog.objects.filter(name__contains="blog")
    if request.method == "POST":
        blog.title = request.POST["title"]
        return redirect("{% url 'blog:details_post_view' blog.id %}")

    return render(request, "main/index.html", {"blog" : blog})

BlogWebsite/blog/templates/blog/add_post.html
{% extends 'main/base.html' %}

{% block title %} Add new post {% endblock %}


{% block content %}
  
    <div class="row aa">

        <div class="col" >
            <h2>Adding post</h2>

            <form  action="{% url 'blog:add_post_view' %}" method="post" class="d-flex flex-column gap-2">
                {% csrf_token %} 
                <label>Title: </label>
                <input type="TextChoices" name="title" />

                <label>Content: </label>
                <textarea name="Content"></textarea> 
          
                <label>Category: </label>
                <select name="category">
                    {% for value, title in category_choices %}
                        <option value="{{value}}">{{title}}</option>
                    {% endfor %}
                </select>


                <label>Publish Date:</label>
                <input type="date" name="publish_date" />

                <input type="submit" value="Add Post" class="btn btn-primary"/>

            </form>

        </div>

    </div>
 
{% endblock %}

BlogWebsite/blog/templates/blog/all_post.html
{% extends 'blog/base.html'%}
{% load static%}


{%block title%} all post {%endblock%}


{%block background%}

<div>
    <div style="background-image: url('/static/images/add_background.jpg');" class="background effect"></div>
</div>

{%endblock%}

{%block content%}

<div class="row">
{% for p in posts%}

<div class="col-4 mt-4 ">
  <div class="d-flex flex-column gap-3 border border-1 rounded-4 p-4 mt-1 h-100 bg-warning">
      <h3>{{ p.title }}</h3>
      <div class="d-flex justify-content-between align-items-center">
          <h6>{{ p.content }}</h6>
          <div class="d-flex gap-1 align-items-center">
              <h6 class="p-0 m-0"> {{p.category}}</h6>
          </div>     
      </div>
      <a href="{% url 'blog:detail_post_view' p.id %}"> <button type="button" class=" btn text-decoration-none bg-danger"> <h5> Read more </h5> </button></a>
      <div>

      </div>
  </div>
</div>



{% endfor %}
</div>





{%endblock%}

BlogWebsite/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>

<html>
    <head>

        <title> {%block title%} {%endblock%} </title>

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
        <link rel="stylesheet" href="/static/styles/main.css"/>



    </head>

    <body>


        
        <nav class="navbar navbar-expand-lg navbar-ligt border-bottom j">
            <div class="container-fluid ">

              <a style="color: black; font-size: 35px;" class="navbar-brand " href="/"> BlogWebsite </a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                  <li class="nav-item">
                    <a style="color: black; font-size: 20px;" class="nav-link" href="/"> Home </a>
                  </li>
                  <li class="nav-item">
                    <a style="color: black; font-size: 20px;" class="nav-link" href="{% url 'blog:add_post_view'%}"> Add a post </a>
                  </li>
                  <li class="nav-item">
                    <a style="color: black; font-size: 20px;" class="nav-link" href="{% url 'blog:all_post_view'%}" > Display post </a>
                  </li>
                </ul>
              </div>

              <form class="d-flex" role="search" action="{% url 'blog:search_result_view'%}" method="post">
                {% csrf_token %}
                <input class="form-control me-2" type="search" placeholder="Search" required aria-label="Search" name="search_query">
                <button class="btn btn-outline-warning" type="submit">Search</button>
              </form>
            </div>
          </nav>

        <div>
            {%block background%}

            {%endblock%}
        </div>


        <div>
            {%block content%}

            {%endblock%}
        </div>






        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>

    </body>


</html>

BlogWebsite/blog/templates/blog/detail_posts.html
{% extends 'blog/base.html'%}
{% load static%}


{%block title%} Detail of post {{posts.title}} {%endblock%}

{%block background%}

<div>
    <div style="background-image: url('/static/images/add_background.jpg');" class="background effect"></div>
</div>

{%endblock%}


{%block content%}


<div class="container"> 
    <div class="d-flex flex-column gap-2 border border-3 mt-5 ps-3 " style="background-color: white; opacity: 0.9;">
        <h1> #{{posts.title}}</h1>
        <div class="d-flex justify-content-between">
            <h3> {{posts.category}} </h3>



           

        </div>
        <p style="font-size: 30px;"> {{posts.content}}</p>
    </div>
</div>

<div class="d-flex justify-content-around mt-4">
    <a href="{% url 'blog:update_post_view' posts.id %}" class="btn btn-warning"><h4> Update </h4></a>
    <a href="{% url 'blog:delet_post_view' posts.id %}" class="btn btn-warning"><h4> Delet </h4></a>
</div>


{%endblock%}

BlogWebsite/blog/templates/blog/details_post.html
{% extends 'main/base.html' %}

{% block title %} details {% endblock %}


{% block content%}


<div class="details flex-column gap-2">
    <h2>{{ blog.title }}</h2>
    <div class="d-flex justify-content-between">
        <h3>{{blog.Content}}</h3>
        <div>
            <a href="{% url 'blog:update_post_view' blog.id %}" class="btn btn-warning">Update</a>
            <a href="{% url 'blog:delete_post_view' blog.id %}" class="btn btn-danger">Delete</a>
        </div>
    </div>
    <p>{{blog.category }}</p> 
    
</div>


{%endblock%}

BlogWebsite/blog/templates/blog/home.html
{% extends 'blog/base.html'%}
{%load static%}

{%block title%} Home {%endblock%}

{%block background%}

<div style="background-image: url('/static/images/blog_background.jpg');" class="background effect">

</div>

{%endblock%}


{%block content%}

<div class="container container_home"> 
    <div class="row justify-content-center align-items-center">
      <div class="col-md-10 mt-5  ">
        <div id="carouselExampleCaptions" class="carousel slide">
          <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
          </div>



          <div class="carousel-inner ">
            <div class="carousel-item active">
                <img src="/static/images/home_bacground.jpg" class="d-block w-100 h-100" alt="...">
                <div class="carousel-caption d-none d-md-block pt-4">
                    <h1 style="color: black; font-size: 3rem;"> Welcome to blog website!</h1>
                    <p style="font-size: 2rem; "> you can share your writing on subject that related to technology</p>
                </div>
            </div>
                


            <div class="carousel-item">
            <img src="/static/images/home_bacground.jpg" class="d-block w-100 h-100" alt="...">
              <div class="carousel-caption d-none d-md-block">
                <h1>Add new post to blog website</h1>
                <a href="{% url 'blog:add_post_view'%}"> <button type="button" class="btn btn-info">Add</button></a>
              </div>
            </div>

            
            <div class="carousel-item">
                <img src="/static/images/home_bacground.jpg" class="d-block w-100 h-100" alt="...">

                <div class="carousel-caption d-none d-md-block">
                    <h1> View post available in blog website </h1>
                    <a href="{% url 'blog:all_post_view'%}"> <button type="button" class="btn btn-lg btn-info">View</button></a>

                </div>
            </div>
  
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
      </div>
  
  
  
     
  
    </div>
  </div>

{%endblock%}

BlogWebsite/blog/templates/blog/http404.html
{% extends 'blog/base.html'%}
{% load static%}


{%block title%} Detail of post {{posts.title}} {%endblock%}

{%block background%}

<div>
    <div style="background-image: url('/static/images/Http404.png');" class="background effect"></div>
</div>

{%endblock%}

BlogWebsite/blog/templates/blog/search_result.html
{% extends 'blog/base.html'%}
{% load static%}


{%block title%} Add post {%endblock%}


{%block background%}

<div>
    <div style="background-image: url('/static/images/add_background.jpg');" class="background effect"></div>
</div>

{%endblock%}



{%block content%}

{% if query %}
    <div>
        <div>
        
        {% for post in posts %}
            <div>
                
                <p>{{post.title}}</p>
            </div>
        {% endfor %}
        </div>
    </div>
{% else %}
    <h1>Please enter a search query</h1>

{% endif %}

{%endblock%}

BlogWebsite/blog/templates/blog/ubdate_posts.html
{% extends 'blog/base.html'%}
{% load static%}


{%block title%} update post {{posts.title}} {%endblock%}

{%block background%}

<div>
    <div style="background-image: url('/static/images/add_background.jpg');" class="background effect"></div>
</div>

{%endblock%}


{%block content%}


<div   class="container pt-5"> 

    <div class="row ">
        <div class="col">
            <div class="d-flex flex-column justify-content-center align-items-center mt-5">
            <h1> Adding a new opst</h1> 
            </div>

            <form action="{% url 'blog:add_post_view'%}" method="post" class="d-flex flex-column justify-content-center align-items-center">
                {% csrf_token %} 

                <label style="font-size: 25px;"> Title </label>
                <input size="40" type="text" name="title">


                <label style="font-size: 25px;"> Content </label>
                <textarea rows="4" cols="40" name="content"> </textarea> 



                <label style="font-size: 25px;" > Category </label>
                <select  name="category">
                    {%for value,title in posts.category_choices%} 
                        <option value="{{value}}" {% if Post.category == value %} selected {% endif%} > {{title}}</option>
                    {%endfor%}
                </select>

                <label class="mt-3" style="font-size: 25px;"> Publish Date </label>
                <input type="datetime-local" name="publish_date">

                <input type="submit" value="Add Post" class="btn btn-primary mt-4"/> 

            </form>
        </div>


    </div>

</div>



{%endblock%}

BlogWebsite/blog/templates/blog/update_post.html
{% extends 'main/base.html' %}

{% block title %} Update blog {{ blog.title }} {% endblock %}


{% block content %}
    <div class="row">

        <div class="col">
            <h2>Update blog</h2>

            <form  action="{% url 'blog:update_post_view' blog.id %}" method="post" class="d-flex flex-column gap-2">
                {% csrf_token %} 
                <label>Title: </label>
                <input type="text" name="title" value="{{ blog.title }}"/>

                <label>Content: </label>
                <input type="text" name="Content" value="{{ blog.Content }}"/>

                <label>Category: </label>
                <select name="category">
                    {% for value, title in blog.category_choices %}
                        <option value="{{value}}" {% if blog.category == value %} selected {% endif%}>{{title}}</option>
                    {% endfor %}
                </select>

                <label>Publish Date:</label>
                <input type="date" name="publish_date" value="{{ blog.publish_date.isoformat }}" />

                <input type="submit" value="update blog" class="btn btn-primary"/>

            </form>

        </div>

    </div>

{% endblock %}

BlogWebsite/main/templates/main/add_blog_view.html
{% extends 'main/base.html' %}

{% block title %} Writing Page {% endblock %}

{% block content %}
<div class="row justify-content-center">

  <div class="col-md-6 ">
      <h2>Write your Blog</h2>
      <h6 class="text-center"> Writing Category:<br/>
        Fashion - Beauty - Travel - Personal - Tech<br/>
        Health - Home - Fitness - Education - Food - Entertainment
      </h6>

      <form  action="{% url 'main:add_blog_view' %}" method="post" class="d-flex flex-column gap-2">
          {% csrf_token %} 
          <label>Title: </label>
          <input type="text" name="title" style="background-color: #f9f0e3;" />

          <label>Content: </label>
          <textarea name="content" style="background-color: #f9f0e3;" ></textarea> 
          
          <label>Category: </label>
          <input type="content" name="category" style="background-color: #f9f0e3;" />
          <!--
            <select name="category" style="background-color: #f9f0e3;">
            <option value="Fashion"> Fashion </option>
            <option value="Beauty"> Beauty </option>
            <option value="Travel"> Travel </option>
            <option value="Personal"> Personal </option>
            <option value="Tech"> Tech </option>
            <option value="Health"> Health </option>
            <option value="Home"> Home </option>
            <option value="Fitness"> Fitness </option>
            <option value="Education"> Education </option>
            <option value="Food"> Food </option>
            <option value="Entertainment"> Entertainment </option>
          </select>

          -->

        
          <label>Publish Date:</label>
          <input type="date" name="publish_date" style="background-color: #f9f0e3;"  />

          <input type="submit" value="Add Blog" class="btn " style="background-color: #f1683e;" />
          

      </form>

  </div>

</div>
{% endblock %}

BlogWebsite/main/templates/main/add_post.html
{% extends 'main/base.html' %}

{% block title %}add post {% endblock %}


{% block content %}

<h1>Add New Post</h1>
<form  action="{% url 'main:add_post_view' %}" method="post" class="d-flex flex-column gap-2">
        {% csrf_token %} 
        <label for="title">Title:</label><br>
        <input type="text" id="title" name="title"><br><br>

        <label for="content">Content:</label><br>
        <textarea id="content" name="content"></textarea><br><br>

        <label for="category">Category:</label><br>
        <input type="text" id="category" name="category"><br><br>

        <label for="publish_date">Publish Date:</label><br>
        <input type="datetime-local" id="publish_date" name="publish_date"><br><br>
        <input type="submit" value="Add Post">
    </form>









   
{% endblock %}  

BlogWebsite/main/templates/main/base.html
{%load static%}
<!DOCTYPE html>
<html>
    <head>
        <title> {% block title%}  {%endblock%} </title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@500&family=Tilt+Prism&display=swap" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'styles/main.css' %}" />


    </head>




    <body>

        <nav class="navbar bg-body-tertiary fixed-top">
            <div class="container-fluid">
              <a class="navbar-brand text-warning" href="#" ><img src="/static/images/logo.jpeg" class="bd-placeholder-img rounded-circle" width="50" height="50">  Blog</a> 
              <button class="navbar-toggler text-warning" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="offcanvas offcanvas-end " tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
                <div class="offcanvas-header">
                  <h5 class="offcanvas-title text-warning" id="offcanvasNavbarLabel">My Blog</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                </div>
                <div class="offcanvas-body">
                  <ul class="navbar-nav justify-content-end flex-grow-1 pe-3 ">
                    <li class="nav-item">
                      <a class="nav-link active text-warning" aria-current="page" href="{% url 'main:home_view'%}">Home</a>
                      <a class="nav-link active text-warning" aria-current="page" href="{% url 'blog:all_post_view'%}">Posts</a>
                      <a class="nav-link active text-warning" aria-current="page" href="{% url 'blog:add_post_view'%}">new post</a>
                    </li>
                  </ul>
                  <form role="search">
                    <input class="form-control" type="search" placeholder="Search" aria-label="Search" >
                  </form>
                </div>
              </div>
            </div>
          </nav>


        {% block content %}

            {% endblock %}

            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script> 

    </body>
</html>

BlogWebsite/main/templates/main/home.html
{% extends 'main/base.html' %}

{% block title %} Blog Home{% endblock %}


{% block content %}





<div class="row pt-4">
    <div class="col-12 col-md-6 order-2 order-md-1">
        <div class="d-flex flex-column justify-content-center align-items-center h-100">
            <h1>Welcome to the Blog Website</h1>
            <p>Explore and share your thoughts about movies.</p>
           
        </div>

    </div>







   
{% endblock %}     

BlogWebsite/main/templates/main/home_view.html
{% extends 'main/base.html' %}

{% block title %} Home Page {% endblock %}

{% block content %}
<div class="container-lg border border-black d-flex justify-content-center">
    <img src="/static/images/logo.png" alt="Bootstrap" width="50" height="50">
    <div>
        <h4 class="ms-3 mt-3">About Heavy Pen Blog</h4>
        <h5 class="mt-5 text-center"> Heavy Pen Blog is a creative writer's getaway from standard writing sources,<br/> allowing them to write about whatever they desire.  </h5>
    </div>
</div>
{% for blog in blogs %}
<div class="accordion accordion-flush d-flex justify-content-start ms-4 mt-4" id="accordionFlushExample" >
    <div class="accordion-item border border-white rounded-4" >
        <h2 class="accordion-header">
            <button class="accordion-button collapsed" style="background-color: #f9e6cd;" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
                {{ blog.title }}
            </button>
        </h2>
        <div id="flush-collapseOne" style="background-color: #f9ecdb;" class="accordion-collapse collapse" data-bs-parent="#accordionFlushExample">
            <div class="accordion-body">
                <div style="display: inline;">
                    <h6> {{ blog.category }} </h6>
                    <h6> {{ blog.publish_date }}</h6>
                </div>

                {{ blog.content }}
            </div>
        </div>
    </div>
</div>
{% endfor %}

{% endblock %}

BlogWebsite/main/templates/main/index.html
{% extends 'main/base.html' %}

{% block title %} My Blog {% endblock %}


{% block content %}

<div class="row pt-4">
    <div class="col-12 col-md-6 order-2 order-md-1">
        <div class="d-flex flex-column justify-content-center align-items-center h-100 text-warning">
            <h1>Welcome to my blog</h1>
            <p> This is my favourite blog to read!</p>
            <a  href="{% url 'blog:all_post_view' %}" class="btn btn-info rounded rounded-5">view the posts</a>
        </div> 

    </div>
    <div class="col-12 col-md-6 g-0 order-1 order-md-2">
        <img class="w-100 rounded-4" src="/static/images/home5.jpeg" />
    </div>
</div>



{% endblock %}