Bolg/Bolg/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("main.urls"))
]

Bolg/main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path('', views.home_page_view, name="home_page_view"),
    path('add/', views.add_new_view, name="add_new_view"),
    path('all/', views.all_new_view, name="all_new_view"),
    path('detalis/<new_id>/', views.detail_view, name="detail_view"),
    path('delet/<new_id>/', views.delete_view, name="delete_view"),
    path('updeat/<new_id>/', views.updeat_view, name="updeat_view"),
    path("search/", views.search_view, name="search_view"),


]

Bolg/main/models.py
from django.db import models

# Create your models here.

class NewBlog(models.Model):
        
    title = models.CharField(max_length=2048)
    content = models.TextField()
    category = models.CharField(max_length=2048)
    publish_date = models.DateTimeField()

Bolg/main/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse
from .models import NewBlog
# Create your views here.
def home_page_view(request: HttpRequest):
    return render(request, "main/homePage.html")


def add_new_view(request: HttpRequest):

    if request.method == "POST":
        #adding a book
        new_book = NewBlog(title=request.POST["title"], content=request.POST["content"], category=request.POST["category"], publish_date=request.POST["publish_date"])
        new_book.save()

        return redirect("main:all_new_view")
    return render(request, 'main/add_new.html')

    
def all_new_view(request: HttpRequest):

    news = NewBlog.objects.all()

    return render(request, "main/all_new.html", context = {"news" : news})


def detail_view(request : HttpRequest, new_id):
    
    #to get a single entry in the database
    new = NewBlog.objects.get(id=new_id)

    return render(request, "main/detali.html", {"new" : new})


def updeat_view(request:HttpRequest, new_id):
    new = NewBlog.objects.get(id=new_id)
    if request.method == "POST":
        new.title = request.POST["title"]
        new.content = request.POST["content"]
        new.category = request.POST["category"]
        new.save()
        return redirect("main:all_new_view")
    return render(request, "main/updeat.html", {"new" : new})


def delete_view(request:HttpRequest , new_id):

    new = NewBlog.objects.get(id=new_id)
    new.delete()
    
    return redirect ("main:all_new_view")

def search_view(request):
    if request.method == "POST":
        search_query = request.POST['search_query']
        posts = NewBlog.objects.filter(title__contains=search_query)
    return render(request, "main/all_posts.html", {'query':search_query, 'posts':posts})

Bolg/main/templates/main/add_new.html
{% extends 'main/base.html' %}

{% block title %} Add new  {% endblock %}


{% block content %}
    <div class="row">

        <div class="col pt-5" style="margin-left: 500px;">
            <h2>Adding New Bolg</h2>

            <form  action="{% url 'main:add_new_view' %}" method="post" class="d-flex flex-column gap-2">
                {% csrf_token %} 
                <div class="row">
                    <div class="col-12 pt-3">
                        <label>Title: </label>
                        <input type="text" name="title" />
                    </div>
                    <div class="col-12 pt-3">
                        <label>content: </label>
                        <textarea name="content"></textarea> 
                    </div>
                    <div class="col-12 pt-3">
                        <label >category: </label>
                        <select name="category">
                            <option value="Fashion blog"> Fashion blogs </option>
                            <option value="Music blog"> music blog </option>
                            <option value="Travel blog"> travel blog </option>
                            <option value="Beauty blog"> beauty blog </option>
                            <option value="Business blog"> Business blog </option>
                        </select>
                    </div>
                    <div class="col-12 pt-3">
                        <label>Publish Date:</label>
                        <input type="date" name="publish_date" />
                    </div>
                    <div class="col-12 pt-3">
                        <button class="btn btn-primary" value="Add Book" type="submit" style="margin-left: 80px;">Submit form</button>
                    </div>
                </div>

            </form>

        </div>

    </div>
{% endblock %}

Bolg/main/templates/main/all_new.html
{% extends 'main/base.html' %}


{% block title %} All  {% endblock %}

{% block content %}


<h1>New Bolg</h1>
<div class="row">
{% for new in news %}
<div class="col-4 mt-4">
    <div class="d-flex flex-column gap-3 border border-1 shadow rounded-4 p-4 mt-1  h-100">
        <h3>{{ new.title }}</h3>
        <div class="d-flex justify-content-between align-items-center">
            <h6>{{new.publish_date}}</h6>
            <div class="d-flex gap-1 align-items-center">
                <h6 class="p-0 m-0"> {{ new.content }}</h6>
                <span class="material-symbols-outlined">star</span>
            </div>
            
        </div>

        <a href="{% url 'main:detail_view' new.id %}" class="d-flex justify-content-between text-decoration-none">
            <h5>more</h5>
            <span class="material-symbols-outlined"> arrow_forward</span>
        </a>
        
       
    </div>
</div>
   
{% endfor %}
</div>

{% endblock %}

Bolg/main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %} {% endblock %}</title>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
        <link rel="stylesheet" href="{% static 'styles/main.css' %}" />
    
    </head>

    <body >

        <nav class="navbar navbar-expand-lg bg-body-tertiary rounded" aria-label="Eleventh navbar example">
            <div class="container">
              <a class="navbar-brand" href="/">New Blog</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample09" aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
      
              <div class="collapse navbar-collapse" id="navbarsExample09">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:all_new_view' %}">All Books</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:add_new_view' %}">Add Book</a>
                  </li>
                  
                </ul>
                <form class="d-flex" role="search" method="POST" action="{% url 'main:search_view' %}">
                  {% csrf_token %}
                  <input
                     class="form-control me-2"
                     type="search"
                     placeholder="Search"
                     name="search_query"
                     required aria-label="Search"
                  >
                  <button class="btn btn-outline-success" type="submit">Search</button>
                 </form>
        
              </div>
            </div>
          </nav>

      
            {% block content %}

            {% endblock %}

        
    
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    </body>
</html>

Bolg/main/templates/main/detali.html
{% extends 'main/base.html' %}

{% block title %} Details {{ book.title }} {% endblock %}

{% block content %}
<div class="d-flex flex-column gap-2">
    <h1>{{ new.title }}</h1>
    <div class="d-flex justify-content-between">
        <h3>{{new.content}}</h3>
        <div>
            <a href="{% url 'main:updeat_view' new.id %}" class="btn btn-warning">Update</a>
            <a href="{% url 'main:delete_view' new.id %}" class="btn btn-danger">Delete</a>
        </div>
    </div>
    <p>{{ new.category }}</p>
</div>
{% endblock %}

Bolg/main/templates/main/homePage.html
{% extends 'main/base.html' %}

{% block title %} Book Club for Books Lovers {% endblock %}


{% block content %}

<div class="row pt-4">
    <div class="col-12 col-md-6 order-2 order-md-1">
        <div class="d-flex flex-column justify-content-center align-items-center pt-5 h-100">
            <h1>Welcome to New Blog</h1>
        </div>

    </div>
    <div class="col-12 col-md-6 g-0 order-1 order-md-2">
        <img class="w-100 rounded-4" src="/static/images/blog.jpg" />    </div>
</div>

<div class="container">
    <div class="row" style="margin-top: 50px; margin-left:100px ;">
        <div class="col ">
            <h2> To View the new blog </h2>
            <a href="{% url 'main:all_new_view' %}" class="btn btn-success rounded rounded-5"style="margin-left:100px ;"> view new</a>

            
        </div>

        <div class="col">
            <h2> To Add the new blog </h2>
            <a href="{% url 'main:add_new_view' %}" class="btn btn-success rounded rounded-5"style="margin-left:100px;">add new</a>

        </div>


    </div>
</div>



{% endblock %}

Bolg/main/templates/main/updeat.html
{% extends 'main/base.html' %}

{% block title %} update new  {% endblock %}


{% block content %}

<div class="container ">
    <div class="row ">
        <div class="d-flex flex-column gap-3 border border-3 shadow rounded-4 p-4 mt-5  h-100 justify-content-between align-items-center"  >
            <h2>update New Bolg</h2>
            <div class="justify-content-between align-items-center">
                <form  action="{% url 'main:updeat_view' new.id %}" method="post" class="d-flex flex-column gap-2">
                    {% csrf_token %} 
                    <div class="row">
                        <div class="justify-content-between align-items-center">
                            <div class="col-12">
                                <label>Title: </label>
                                <input type="text" name="title"  value="{{ new.title }}" />
                            </div>
                            <div class="col-12 pt-3">
                                <label>content: </label>
                                <textarea name="content"> {{ new.content }}</textarea> 
                            </div>
                            <div class="col-12 pt-3">
                                <label >category: </label>
                                <select name="category">
                                    <option value="Fashion blog"> Fashion blogs </option>
                                    <option value="Music blog"> music blog </option>
                                    <option value="Travel blog"> travel blog </option>
                                    <option value="Beauty blog"> beauty blog </option>
                                    <option value="Business blog"> Business blog </option>
                                </select>
                            </div>
                            <div class="col-12 pt-3">
                                <button class="btn btn-primary" value="update new" type="submit" >Submit form</button>
                            </div>
                        </div>
                    </div>

                </form>
            </div>

        </div>

    </div>
</div>
{% endblock %}