MyBlogSite/MyBlogSite/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include("blog.urls")),
]

MyBlogSite/blog/urls.py
from django.urls import path
from blog import views

app_name = "blog"

urlpatterns = [
    path('', views.home, name='home'),
    path('posts/', views.posts, name='posts'),
    path('add_post/', views.add_post, name='add_post'),
]

MyBlogSite/blog/models.py
from django.db import models

class Post(models.Model):
    CATEGORY_CHOICES = [
        ('Technology', 'Technology'),
        ('Travel', 'Travel'),
        ('Food', 'Food'),
        ('Lifestyle', 'Lifestyle'),
    ]

    title = models.CharField(max_length=200)
    content = models.TextField()
    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES)
    publish_date = models.DateTimeField()
    photo = models.ImageField(upload_to='post_photos/', null=True, blank=True)

    def __str__(self):
        return self.title

MyBlogSite/blog/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'category', 'publish_date', 'photo']

MyBlogSite/blog/views.py
from django.shortcuts import render, redirect
from .models import Post
from .forms import PostForm
from django.http import HttpRequest, HttpResponse

def home(request: HttpRequest):
    return render(request, 'blog/home.html')

def posts(request: HttpRequest):
    posts = Post.objects.all()
    return render(request, 'blog/posts.html', {'posts': posts})

def add_post(request:HttpRequest):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('posts')  # Redirect to the posts page after successful submission
    else:
        form = PostForm()
    return render(request, 'blog/add_post.html', {'form': form})

MyBlogSite/blog/templates/blog/add_post.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}
<div class="content"> 
    <h1> add your own experince </h1>
</div>


<section class="container">
    <div class="slider-wraped">
        <div class="slider-text">
            <h1>Add New Post</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Add Post</button>
        </form>
        </div>
        </div>
        </section>
{% endblock %}

MyBlogSite/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}my Blog{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body>

    <div class="banner">
        <div class="navbar">
            <ul>
                <li><a href="{%  url 'blog:home'%}">Home</a></li>
                <li><a href="{%  url 'blog:posts'%}">Posts</a></li>
                <li><a href="{%  url 'blog:add_post'%}">add Post</a></li>

            </ul>
        </div>
    </div>

    <div class="hero">
        <video autoplay muted loop plays-inline class="backVid" >
            <source src="{% static 'videos/IMG_3436.mp4' %}" type="video/mp4">
            Your browser does not support the video tag.
        </video>
    </div>
    
{%block video%}
   
    {%endblock%}
        <div class="content-overlay">
            {% block content %}
            {% endblock %}
            
        </div>

</body>
</html>

MyBlogSite/blog/templates/blog/home.html
{% extends 'blog/base.html' %}
{% load static %}

{%block content%}
    <div class="content">
        <h1> Welcome to <br> My Blog </h1>
        </div>
{%endblock%}
        

MyBlogSite/blog/templates/blog/posts.html
{% extends 'blog/base.html' %}
{% load static %}
{% block title %}posts{% endblock %}


{% block content %}
<div class="content">
    <h1>scroll down<br>to see the posts</h1>
</div>

<section class="container">
    <div class="slider-wraped">
        <div class="slider-text">
            <h2 class="slide-h">personal <br> experince</h2>
            <p class="slider-p">here is some pictures i took to the places i went in jeddah</p>
        </div>
     <div class="slider">
        <img id="1" src="{% static 'images\photo_2023-08-25_17-13-20.jpg' %}" alt="1">
        <img id="2" src="{% static 'images/photo_2023-08-25_17-13-27.jpg' %}" alt="2">
        <img id="3" src="{% static 'images/photo_2023-08-25_17-13-30.jpg' %}" alt="3">
        <img id="4" src="{% static 'images/photo_2023-08-25_17-13-33.jpg' %}" alt="4">
        <img id="5" src="{% static 'images/photo_2023-08-25_17-13-35.jpg' %}" alt="5">
        <img id="6" src="{% static 'images/photo_2023-08-25_17-13-38.jpg' %}" alt="6">
        <img id="7" src="{% static 'images/photo_2023-08-25_17-13-40.jpg' %}" alt="7">
        <img id="8" src="{% static 'images/photo_2023-08-25_17-13-42.jpg' %}" alt="8">
        <img id="9" src="{% static 'images/photo_2023-08-25_17-13-43.jpg' %}" alt="9">
        <img id="10" src="{% static 'images/photo_2023-08-25_17-13-45.jpg' %}" alt="10">
        <img id="11" src="{% static 'images/photo_2023-08-25_17-13-47.jpg' %}" alt="11">
        <img id="12" src="{% static 'images/photo_2023-08-25_17-13-49.jpg' %}" alt="12">
        <img id="13" src="{% static 'images/photo_2023-08-25_17-13-50.jpg' %}" alt="13">
     </div>
     <div class="slider-nav">
        <a href="#1"></a>
        <a href="#2"></a>
        <a href="#3"></a>
        <a href="#4"></a>
        <a href="#5"></a>
        <a href="#6"></a>
        <a href="#7"></a>
        <a href="#8"></a>
        <a href="#9"></a>
        <a href="#10"></a>
        <a href="#11"></a>
        <a href="#12"></a>
        <a href="#13"></a>
     </div>   
    </div>

</section>
{%endblock%}